name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Create virtual environment
        run: python -m venv venv

      - name: Install dependencies (app + test)
        run: |
          . venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # Ensure pytest is present even if not listed in requirements
          pip install -U pytest

      - name: Make test script executable
        run: chmod +x ./run_test.sh

      - name: Run tests
        run: |
          . venv/bin/activate
          ./run_test.sh
